name: Amnesia

#Event trig
on: workflow_dispatch

env:
  Name: Billal
  ENTREPRISE: BillDev

jobs:
  say_hello:
    runs-on: ubuntu-latest
    env:
      DAY: mardi
    steps:
      - name: "Dit bonjour"
        run: echo "Bonjour $Name ! Bienvenue chez $ENTREPRISE et bon $DAY à toi !"
      - name: "Dit le jour"
        run: echo "Oui, aujourd'hui c'est $DAY !"
        
  say_goodbye:
    runs-on: ubuntu-latest
    needs: say_hello
    steps:
      - name: "Dit au revoir"
        run: echo "Au revoir $Name ! A bientôt chez $ENTREPRISE !"